spring:
  application:
    name: gateway-platform
  cloud:
    gateway:
      locator:
        enabled: false
        lower-case-service-id: true
  redis:
    host: localhost
    port: 6379
    database: 0
  main:
    allow-bean-definition-overriding: true

server:
  port: 20004

# 开启所有的actuator-endpoint
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        # include: healthy,info,xxx自己需要的放开的服务
        include: '*'
    security:
      enabled: false

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/

