server:
  port: 10002

spring:
  datasource:
    # 数据源的相关配置 拆分数据源到不同的，或者独立的schema
    url: jdbc:mysql://localhost:3306/foodie-shop-dev?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true
#    url: jdbc:mysql://localhost:3306/foodie-cloud-item?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true
    password: root
  redis:
    database: 0
    host: localhost
    port: 6379
  zipkin:
    discoveryClientEnabled: true
    enabled: false
    locator:
      discovery:
        enabled: true
  #stream 配置
  cloud:
    stream:
      bindings:
        force-logout-consumer:
          destination: force-logout-topic
          group: force-logout-group
          consumer:
            max-attempts: 2
        force-logout-producer:
          detination: force-logout-topic

    base-url: http://ZIPKIN-SERVER/
    #以HTTP上传数据到zipkin
    # 由于 bus依赖项导入了rabbitmq的依赖项，zipkin会默认使用mq
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# 开启所有的actuator-endpoint
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        # include: healthy,info,xxx自己需要的放开的服务
        include: '*'
    security:
      enabled: false

hystrix:
  command:
    #有的属性是默认值
    default:
      fallback:
        enabled: true
      circuitBreaker:
        enabled: true
        # 超过50%的错误，那么开启熔断
        errorThresholdPercentage: 40
        #5个请求之后才开始统计
        requestVolumeThreshold: 5
        # 进入10秒之后进入半开状态
        sleepWindowInMilliseconds: 10000
        # forceClosed,forceOpen 强制关闭、开启熔断机制
      execution:
        timeout:
          enabled: true
        # 可以指定隔离方式是线程池还是信号量
        isolation:
          thread:
            interruptOnTimeout: true
            interruptOnFutureCancel: true
            timeoutInMilliseconds: 10000
      metrics:
        rollingStats:
          #时间窗口统计
          timeInMilliseconds: 20000
          # 时间窗口内桶的个数
#          numBuckets: 10
#        rollingPercentile:
#          #时间窗口统计
#          timeInMilliseconds: 20000
#          numBuckets: 10
#          bucketSize: 300
    # 照它的方法，覆盖其他属性
    loginFail:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 3000