spring:
  application:
    name: gateway-platform
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            # 返回的资源共享给请求资源
            allowed-origins:
            - "http://localhost:8080"
            - "http://shop.z.mukewang.com:8080"
            - "http://center.z.mukewang.com:8080"
            - "http://shop.z.mukewang.com"
            - "http://center.z.mukewang.com"
            - "*"
            # 比如cookie，authorization之类的认证信息
            allow-credentials: true
            allowed-headers: "*"
            allowed-methods: "*"
            expose-headers: "*"
            # 表示options可以在浏览器缓存多长时间
            max-age: 600
      locator:
        enabled: false
        lower-case-service-id: true
  redis:
    host: localhost
    port: 6379
    database: 0
  main:
    allow-bean-definition-overriding: true

server:
  port: 20004

# 开启所有的actuator-endpoint
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        # include: healthy,info,xxx自己需要的放开的服务
        include: '*'
    security:
      enabled: false

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/

